### ISSUE TITLE
Allow Python > 3.8

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricksdev#11]
We currently require `python = "~3.8"`, so users with 3.9 have to install `pyenv`.

@dlech , I think we did this due to a limitation in `bleak` at the time. Do you know if this has been resolved?

**Comment by dlech** [comment]
No, it hasn't been resolved yet.

**Comment by dlech** [comment]
Would also be nice to change the minimum version to 3.7 for Raspberry Pi: https://github.com/pybricks/support/issues/342

**Comment by dlech** [comment]
Bleak should be ready for 3.9 in the next release, whenever that is (could be sooner than later).

**Comment by dlech** [comment]
Fixed in https://github.com/pybricks/pybricksdev/releases/tag/v1.0.0-alpha.10
