### ISSUE TITLE
DFU restore is broken

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricksdev#12]
The device is currently specified [like this](https://github.com/pybricks/pybricksdev/blob/fd7469ac9bbacf79427b8f954593e096f2d63953/pybricksdev/dfu.py#L109):

```
                f"{SPIKE_PRIME_DEVICE},{MINDSTORMS_INVENTOR_DEVICE}",
```

which does not seem to work on Ubuntu.

It does work when simply doing:

``
SPIKE_PRIME_DEVICE
``

**Comment by dlech** [comment]
Fixed in c3d79a1.
