### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricksdev#2]
See https://github.com/pybricks/support/issues/64

**Comment by laurensvalk** [comment]
Confirmed, I'll look into it.

The good news is that the (slow) `discover` does work, so we can look how it works internally or just use a finite time search.

**Comment by laurensvalk** [comment]
Besides discovery, there's this. We could just drop this feature since we can probably live without it a callback on server disconnect:

```
File "c:\users\laure\desktop\pybricksdev\.venv\lib\site-packages\bleak\backends\dotnet\client.py", line 216, in set_disconnected_callback
    raise NotImplementedError("This is not implemented in the .NET backend yet")
NotImplementedError: This is not implemented in the .NET backend yet
```

**Comment by laurensvalk** [comment]
Skipping those, downloading and run also works with Python 3.8 and bleak 0.7, which is cool.

I'll assign this to me to clean up the Windows part.

**Comment by laurensvalk** [comment]
Found the cause and a patch -  'get_discovered_devices' and `discover` in bleak are almost identical but there's one tiny mismatch. I'll look into some more detail later and we might be able to submit the patch.

@dlech , is there anything on the master branch of our `bleak` fork left that we need to keep? Else I'll just force push their new master and apply the patch.

**Comment by dlech** [comment]
Please rename our current master branch so we don't lose it. Call it `0.6.x-fixes` or something like that.

**Comment by laurensvalk** [comment]
ack

**Comment by dlech** [comment]
Another aspect of Windows support is that CTRL+C is handled differently (if I am remembering correctly). https://github.com/pybricks/support/issues/78

**Comment by laurensvalk** [comment]
Downloading and running should be working on windows now - fw update not yet. After erasing flash successfully it fails to start writing the data (unreachable).

**Comment by GianCann** [comment]
@laurensvalk I managed to load the firmware from Windows, without problems.
I only commented on the line relative to disconnection callback function, and matched the discovery with the Bluetooth address instead of name.

**Comment by laurensvalk** [comment]
Those parts work for me too. But one Windows is not all Windows.

**Comment by laurensvalk** [comment]
Windows doesn't seem very self confident. It thinks it is unable to send the erase message when it did so just fine. The firmware is indeed erased and the light turns off, but Windows does not proceed:


```
2020-07-01 20:06:10,845:   DEBUG: Erasing flash.
2020-07-01 20:06:10,845:   DEBUG: Clear and prepare reply
2020-07-01 20:06:10,851:   DEBUG: Make and write request
2020-07-01 20:06:10,852:   DEBUG: TX CHUNK: bytearray(b'\x11'), with response

```
Then it freezes and after a while goes:

```
Exception has occurred: BleakError
Could not write value bytearray(b'\x11') to characteristic 00001626-1212-efde-1623-785feabcd123: Unreachable
  File "C:\Users\laure\Desktop\pybricksdev\pybricksdev\ble.py", line 169, in write
    await self.client.write_gatt_char(
  File "C:\Users\laure\Desktop\pybricksdev\pybricksdev\flash.py", line 184, in bootloader_request
    await self.write(data, delay, request.write_with_response)
```



expected

```
2020-07-01 20:02:26,379:   DEBUG: Erasing flash.
2020-07-01 20:02:26,379:   DEBUG: Clear and prepare reply
2020-07-01 20:02:26,379:   DEBUG: Make and write request
2020-07-01 20:02:26,380:   DEBUG: TX CHUNK: bytearray(b'\x11'), with response
2020-07-01 20:02:29,186:   DEBUG: DATA bytearray(b'\x11\x00')
2020-07-01 20:02:29,235:   DEBUG: Awaiting reply
2020-07-01 20:02:29,236:   DEBUG: Erase(result=0
```

**Comment by dlech** [comment]
Flashing firmware on Windows works now.
