### ISSUE TITLE
v1.0.0a29 run command not working

### ISSUE THREAD

**Issue by NicoTheCode** [pybricks/pybricksdev#36]
Hi guys,

I am using an Intel Macbook and I installed v1.0.0a29. If I am trying to execute the "run" command pybricksdev connects to the robot and uploads the file but it does not execute.

I get the **error message "ValueError: incompatible .mpy file"**

However, downgrading to v1.0.0a28 fixes the issue.

Maybe, there is a bug in the newest revision.

**Comment by laurensvalk** [comment]
Which firmware is installed on the hub?

To find out, run:

```python
from pybricks import version
print(version)
```

With the default settings, the latest pybricksdev requires the latest firmware as well. You can get the latest firmware via https://beta.pybricks.com/

**Comment by NicoTheCode** [comment]
It's "v3.1.0-110-gfedf09ed on 2022-01-17"
I installed it using install.pybricks.com

Now I installed it with beta.pybricks.com and got "v3.2.0b3 on 2022-07-20".
And now it works with the newest pybricksdev version (v1.0.0a29)

Thank you for the fast support👍🏻
Btw I love the pybricks project!

**Comment by laurensvalk** [comment]
Glad to hear it!

And thanks for asking. This is a good reminder that we should make install.pybricks.com automatically redirect to the new beta and eventually remove the subdomain altogether.
