### ISSUE TITLE
Fix Python version

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricksdev#5]
Recently the Python requirement was reduced to 3.6, and yet 3.8 features were used, like `importlib`.

We might want to fix the Python version or place an upper limit so we don't use features that don't actually exist in the versions that are supposed to work, or resolve it some other way.

This package is currently broken on Ubuntu 18.04, for example.

**Comment by GianCann** [comment]
I'm trying to configure a new virtualbox with Ubuntu 18.04 to use pybricksdev (the BLE flashing procedure doesn't work on Windows) but I'm going crazy with the various versions of python...

**Comment by dlech** [comment]
I have read that pythonnet (needed for bleak on Windows) now works on Python 3.8. So it should be OK to make 3.8 the minimum (and maximum) requirement. `~3.8` should do the trick.

BlueZ on Ubuntu 18.04 is too old anyway, so we probably don't want to support that.

**Comment by dlech** [comment]
Also need to update to `bleak` `~0.7` at the same time.

**Comment by laurensvalk** [comment]
Done in https://github.com/pybricks/pybricksdev/commit/3f3380224932d5d74e9958d28169cd845b46bc45
