### ISSUE TITLE
From zero to flashed, complete instructions for Ubuntu

### ISSUE THREAD

**Issue by pivan76** [pybricks/pybricksdev#7]
@dlech , as someone may get stuck, here and there, I've prepared a bit more detailed walk-through for your convenience to flash a Control+ Hub with a freshly built firmware, the complete workflow in a single place.

Enjoy!

```
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python-openssl

mkdir PyBricks (or your choice)
cd PyBricks
curl https://pyenv.run | bash

```
edit  ~/.bashrc so that last lines are:

```
# pyenv & poetry paths you'll need later on
export PATH="/home/<user>/.pyenv/bin:/home/<user>/.poetry/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

```
Then restart your terminal or, just issue:

`exec "$SHELL"`

Clone the code base to build the firmware you'll upload, if you don't have a firmware.zip:

```
git clone https://github.com/pybricks/pybricks-micropython
cd pybricks-micropython/
make
make cplushub
```
Clone pybricksdev as per instructions, install Python 3.8.2 and check it, then install poetry:
```
git clone https://github.com/pybricks/pybricksdev.git
cd pybricksdev
pyenv install 3.8.2
python -V 
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
poetry install
```

Skip this if you're fine with Bluetooth on Linux.
Check you have a working bluetooth dongle with the command `lsusb` , you should see a line similar to this: 

```
Bus 001 Device 002: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0
```
Power-on your LEGO hub, launch the command line tool `bluetoothctl`, then issue a `scan on`:

```
[NEW] Controller 00:02:72:3F:BC:F3 <yourpc> [default]
Agent registered

[bluetooth]# scan on
Discovery started
[CHG] Controller 00:02:72:3F:BC:F3 Discovering: yes
[NEW] Device 90:84:**:**:**:3E Pybricks Hub
[NEW] Device DB:A9:**:**:**:19 Mi Smart Band 4
[CHG] Device DB:A9:**:**:**:19 UUIDs: 0000fee0-0000-1000-8000-0080********

```
(it is always a good idea to have other BLE gears if avaialble in the area, just to double-check everything is fine)

To flash, first power off your hub.
Prepare the command below (and don't hit Enter) in your shell as you're supposed to have just two hand.
`poetry run pybricksdev flash ../pybricks-micropython/bricks/cplushub/build/firmware.zip -d 15
`
Press and keep pressed the green button until it flashes multicolor (red green blue).
Mind the batteries, of course you checked there's plenty of charge in them.
Now run the command above with Enter.

It is safe to remove your finger from the green button once you see the progress bar moving after the update, now it is uploading the firmware (or when your finger becomes blue and cold, whichever comes first).

```
Creating firmware
Searching for LEGO Bootloader
Found: 90:84:**:**:**:3E
Connecting to 90:84:**:**:**:3E
Connected successfully!
Erasing flash and starting update
100%|███████████████████████████████████████████████████| 157k/157k [02:41<00:00, 971B/s]

```
You're done!

**Comment by dlech** [comment]
This is documented in the README now.
