### ISSUE TITLE
I cannot install pybricksdev

### ISSUE THREAD

**Issue by kajr0s** [pybricks/pybricksdev#72]
Windows 11
python 3.12.1

> pip install pybricksdev
Collecting pybricksdev
  Using cached pybricksdev-1.0.0a17-py3-none-any.whl (196 kB)
Collecting aioserial<2.0.0,>=1.3.0 (from pybricksdev)
  Using cached aioserial-1.3.1.tar.gz (9.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting appdirs<2.0.0,>=1.4.4 (from pybricksdev)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting argcomplete<2.0.0,>=1.11.1 (from pybricksdev)
  Using cached argcomplete-1.12.3-py2.py3-none-any.whl (38 kB)
Collecting asyncssh<3.0.0,>=2.2.1 (from pybricksdev)
  Using cached asyncssh-2.14.2-py3-none-any.whl.metadata (9.9 kB)
Collecting bleak<0.13.0,>=0.12.1 (from pybricksdev)
  Using cached bleak-0.12.1-py2.py3-none-any.whl (123 kB)
Collecting mpy-cross==1.14 (from pybricksdev)
  Using cached mpy_cross-1.14-py2.py3-none-win_amd64.whl (158 kB)
Collecting prompt-toolkit<4.0.0,>=3.0.18 (from pybricksdev)
  Using cached prompt_toolkit-3.0.43-py3-none-any.whl.metadata (6.5 kB)
Collecting pyusb<2.0.0,>=1.0.2 (from pybricksdev)
  Using cached pyusb-1.2.1-py3-none-any.whl (58 kB)
Collecting semver<3.0.0,>=2.13.0 (from pybricksdev)
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting tqdm<5.0.0,>=4.46.1 (from pybricksdev)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting validators<0.19.0,>=0.18.2 (from pybricksdev)
  Using cached validators-0.18.2-py3-none-any.whl (19 kB)
INFO: pip is looking at multiple versions of pybricksdev to determine which version is compatible with other requirements. This could take a while.
Collecting pybricksdev
  Using cached pybricksdev-1.0.0a16-py3-none-any.whl (195 kB)
  Using cached pybricksdev-1.0.0a15-py3-none-any.whl (197 kB)
  Using cached pybricksdev-1.0.0a14-py3-none-any.whl (197 kB)
  Using cached pybricksdev-1.0.0a13-py3-none-any.whl (196 kB)
  Using cached pybricksdev-1.0.0a12-py3-none-any.whl (196 kB)
  Using cached pybricksdev-1.0.0a11-py3-none-any.whl (195 kB)
Collecting bleak==0.12.0 (from pybricksdev)
  Using cached bleak-0.12.0-py2.py3-none-any.whl (123 kB)
Collecting pybricksdev
  Using cached pybricksdev-1.0.0a10-py3-none-any.whl (195 kB)
INFO: pip is still looking at multiple versions of pybricksdev to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install pybricksdev==1.0.0a10, pybricksdev==1.0.0a11, pybricksdev==1.0.0a12, pybricksdev==1.0.0a13, pybricksdev==1.0.0a14, pybricksdev==1.0.0a15, pybricksdev==1.0.0a16 and pybricksdev==1.0.0a17 because these package versions have conflicting dependencies.

The conflict is caused by:
    pybricksdev 1.0.0a17 depends on winrt<2.0.0 and >=1.0.21033; sys_platform == "win32"
    pybricksdev 1.0.0a16 depends on winrt<2.0.0 and >=1.0.21033; sys_platform == "win32"
    pybricksdev 1.0.0a15 depends on winrt<2.0.0 and >=1.0.21033; sys_platform == "win32"
    pybricksdev 1.0.0a14 depends on winrt<2.0.0 and >=1.0.21033; sys_platform == "win32"
    pybricksdev 1.0.0a13 depends on winrt<2.0.0 and >=1.0.21033; sys_platform == "win32"
    pybricksdev 1.0.0a12 depends on winrt<2.0.0 and >=1.0.21033; sys_platform == "win32"
    pybricksdev 1.0.0a11 depends on winrt<2.0.0 and >=1.0.21033; sys_platform == "win32"
    pybricksdev 1.0.0a10 depends on winrt<2.0.0 and >=1.0.21033; sys_platform == "win32"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by kajr0s** [comment]
The winrt package is missing on windows?

Does this mean that pybricksdev does not work on windows?

**Comment by dlech** [comment]
Answered the same question at https://github.com/orgs/pybricks/discussions/1413
