### ISSUE TITLE
Multi-hub firmware download option

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricksdev#8]
It's easy to miss minor differences between hubs, see e.g. [this one](https://github.com/pybricks/pybricks-micropython/issues/16).

This issue is to add a convenient command line option that will simply update all Pybricks Hubs in the neighborhood, even those not in bootloader mode already.

It is intended for developers, so instead of a `zip` path it will just require the path to `pybricks-micropython`. Since it is all async, all the ingredients are already there.

So the syntax is:

`pybricksdev skynet /path/to/pybricks-micropython`

**Comment by dlech** [comment]
This sounds like something that should be implemented in the `tools` directory of `pybricks-micropython` since it depends on that repository.
